### PR TITLE
Find improvements

### PR DESCRIPTION
**Pull request by swrobel**
I figured it was time to actually solve one of my issues myself. I was delighted by how well-organized the code is and how easy it was to be productive with it! Thank you!!!

This standardizes Find behavior to be more like all major web browsers:

* Adds Find Next/Previous to the menu, along with hotkeys (CtrlOrCmd+(Shift)+G)
* Opens Find dialog and selects text on Find menu item or hotkey (fixes webcatalog/webcatalog#163)
* Closes Find dialog when pressing Escape in the text input
* Update Find bar to use Paper style & be more compact
screen shot 2017-12-21 at 5 14 25 pm

### CODE REVIEW

**Comment by quanglam2807** [comment]
Thanks a lot for helping, @swrobel! I didn't know my code was that good 👍. The PR looks almost perfect for me. If you can fix the linting error, I'll merge the PR.

**Comment by swrobel** [comment]
@quanglam2807 I fixed the rest, but I can't fix [this failure](https://ci.appveyor.com/project/webcatalog/molecule/build/79#L52) as I can't really understand the reason for it. If I change [this line](https://github.com/webcatalog/molecule/pull/10/files#diff-49c49777304d6c5627347755847104b9R429) from `inputRef=` to `ref=` then it passes, but of course it doesn't actually work... Suggestions?

**Comment by swrobel** [comment]
Actually a bit weird, but now I have both `ref` and `inputRef` and it works. I'm pretty sure the `ref` one is pointless because material-ui uses `inputRef`.

**Comment by quanglam2807** [comment]
@swrobel Actually, what it means is that you need to rewrite the component as a function because you don't use `class`'s features.  `ref` requires `class` so when you adds it, the linting script says that it's justifiable for you to use `class` instead of pure function. You just need to rewrite it to something like this:

```js

const FindInPage = (props) => {
  const {
    classes,
    activeMatch,
    matches,
    text,
    inputRef,
    onCloseFindInPageDialog,
    onRequestFind,
    onRequestStopFind,
    onUpdateFindInPageText,
  } = props;

  return (
    <Paper elevation={2} className={classes.root}>
    ---
    </Paper>
  );
};
```

**Comment by swrobel** [comment]
Thanks, that made perfect sense. Fixed!

**Comment by quanglam2807** [comment]
Awesome, @swrobel. I’ll cut a release ASAP.

**Pull request merged**
